<a href="https://colab.research.google.com/github/ZahirNoman/-ZAHIR-NOMAN-.github.io/blob/main/NUMPY.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
a = np.array([1, 4, 5, 7])
type(a)

In [ ]:
a.dtype

In [ ]:
f = np.array([2.1,3.4,6.2,2.3])
f.dtype

In [ ]:
a

In [ ]:
a.ndm

In [ ]:
a.shape

In [ ]:
f.shape

In [ ]:
a.size

In [ ]:
a
f
a+f

In [ ]:
a*f

In [ ]:
a/f

In [ ]:
f**a

In [ ]:
a*10

universal function

In [ ]:
np.sin(a)

In [ ]:
b=np.array([[1, 2, 3, 4],[10,11,12,34]])
b

In [ ]:
b.size

In [ ]:
b.ndim

In [ ]:
b[1, 2] = -6
b


In [ ]:
b[1]


# **INDEXING**
to pick a single (to pick a entire roww or entire column or pick one element from row or a column)

this concept is alo called *SLICING*

***var[lower:upper:step]***

In [ ]:
# a=[1, 4, 5, 7]

a[1:3]

In [ ]:
#grap the first three elements
a[:3]


array([1, 4, 5])

In [ ]:
#grap the last two elements
a[-2:]


array([5, 7])

In [ ]:
#grap every other elements
a[::2]

In [ ]:
c=np.arange(25).reshape(5, 5)
c

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [ ]:
c[:, ::2]                  #red


In [ ]:
c[:, 1::2]                  #red

In [ ]:
c[4, :]                    #yellow

In [ ]:
c[4]

In [ ]:
c[-1, :]

In [ ]:
c[1::2, :3:2]               #blue

array([[ 5,  7],
       [15, 17]])

In [ ]:
a[-2:]         # slicing the last two elements the data values

array([5, 7])

In [ ]:
a[-2:] = [-1, -2]
a              # we can insert an iterable of length of two

array([ 1,  4, -1, -2])

In [ ]:
a[-2:] = 99    # or a scalar value
a